DROP DATABASE FERRETERIAS25
GO
USE FERRETERIAS25
GO
CREATE TABLE FAMILIAS (
FamID INT NOT NULL,
FamNombre NVARCHAR(20) NOT NULL,
FamDescripcion NVARCHAR(20)
)
GO
CREATE TABLE ARTICULOS(
ArtID INT NOT NULL,
ArtNombre NVARCHAR(20) NOT NULL,
ArtDescripcion NVARCHAR(20),
Precio NUMERIC(12,2),
FamID INT NOT NULL
)
GO
CREATE TABLE DETALLE(
Folio INT NOT NULL,
ArtID INT NOT NULL,
Cantidad INT,
Precio NUMERIC(12,2)
)
GO
CREATE TABLE FERRETERIAS(
FerrID INT NOT NULL,
FerrNombre NVARCHAR(20) NOT NULL,
FerrDomicilio NVARCHAR(20) NOT NULL,
FerrTelefono NVARCHAR(10)
)
GO
CREATE TABLE MUNICIPIOS(
MunID INT NOT NULL,
MunNombre NVARCHAR(20) NOT NULL,
Lada NVARCHAR(3) NOT NULL
)
GO
CREATE TABLE COLONIAS(
ColID INT NOT NULL,
ColNombre NVARCHAR(20) NOT NULL,
CP NVARCHAR(10) NOT NULL,
MunID INT NOT NULL
)
GO
CREATE TABLE CLIENTES(
CteID INT NOT NULL,
CteNombre NVARCHAR(20) NOT NULL,
CteApePat NVARCHAR(20) NOT NULL,
CteApeMat NVARCHAR(20) NOT NULL,
CteDom NVARCHAR(20) NOT NULL,
CteCel NVARCHAR(10) NOT NULL,
CteRFC NVARCHAR(13) NOT NULL,
CteCurp NVARCHAR(18) NOT NULL,
CteFechaNacimiento DATETIME,
CteSexo NVARCHAR(1) NOT NULL,
ColID INT NOT NULL
)
GO
CREATE TABLE ZONAS(
ZonaID INT NOT NULL,
ZonaNombre NVARCHAR(20),
ZonaDescripcion NVARCHAR(20)
)
GO
CREATE TABLE EMPLEADOS(
EmpID INT NOT NULL,
EmpNombre NVARCHAR(20),
EmpApePat NVARCHAR(20),
EmpApeMat NVARCHAR(20),
EmpDomicilio NVARCHAR(20),
EmpTelefono NVARCHAR(10),
EmpCelular NVARCHAR(10),
EmpRFC NVARCHAR(13),
EmpCurp NVARCHAR(18),
EmpFechaIngreso DATETIME,
EmpFechaNacimiento DATETIME,
JefeID INT NOT NULL
)
GO
CREATE TABLE VENTAS(
FerrID INT NOT NULL,
Folio INT NOT NULL,
Fecha DATETIME,
CteID INT NOT NULL,
EmpID INT NOT NULL
)
GO
--LLAVES PRIMARIAS
ALTER TABLE FAMILIAS ADD CONSTRAINT PK_FAMILIAS PRIMARY KEY (FamID)
GO
ALTER TABLE ARTICULOS ADD CONSTRAINT PK_ARTICULOS PRIMARY KEY (ArtID)
GO
ALTER TABLE FERRETERIAS ADD CONSTRAINT PK_FERRETERIAS PRIMARY KEY (FerrID)
GO
ALTER TABLE MUNICIPIOS ADD CONSTRAINT PK_MUNICPIOS PRIMARY KEY (MunID)
GO
ALTER TABLE COLONIAS ADD CONSTRAINT PK_COLONIAS PRIMARY KEY (ColID)
GO
ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (CteID)
GO
ALTER TABLE ZONAS ADD CONSTRAINT PK_ZONAS PRIMARY KEY (ZonaID)
GO
ALTER TABLE EMPLEADOS ADD CONSTRAINT PK_EMPLEADOS PRIMARY KEY(EmpID)
GO
ALTER TABLE VENTAS ADD CONSTRAINT PK_VENTAS PRIMARY KEY (Folio)
GO
ALTER TABLE DETALLE ADD CONSTRAINT PK_DETALLE PRIMARY KEY(Folio,ArtID)
GO
--LLAVES EXTERNAS
ALTER TABLE ARTICULOS ADD CONSTRAINT FK_ARTICULOS FOREIGN KEY (FamID) REFERENCES FAMILIAS(FamID)
GO
ALTER TABLE COLONIAS ADD CONSTRAINT FK_COLONIAS FOREIGN KEY (MunID) REFERENCES MUNICIPIOS(MunID)
GO
ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES FOREIGN KEY (ColID) REFERENCES COLONIAS(ColID)
GO
ALTER TABLE EMPLEADOS ADD CONSTRAINT FK_EMPLEADOS FOREIGN KEY (ZonaID) REFERENCES ZONAS(ZonaID)
GO
ALTER TABLE VENTAS ADD CONSTRAINT FK_VENTAS_CLIENTES FOREIGN KEY (CteID) REFERENCES CLIENTES(CteID),
CONSTRAINT FK_VENTAS_EMPLEADOS FOREIGN KEY (EmpID) REFERENCES EMPLEADOS(EmpID),
CONSTRAINT FK_VENTAS_FERRETERIAS FOREIGN KEY (FerrID) REFERENCES FERRETERIAS(FerrID)
GO
ALTER TABLE DETALLE ADD CONSTRAINT FK_DETALLE_ARTICULOS FOREIGN KEY (ArtID) REFERENCES ARTICULOS(ArtID),
CONSTRAINT FK_DETALLE_VENTAS FOREIGN KEY (Folio) REFERENCES VENTAS(Folio)
GO
ALTER TABLE EMPLEADOS ADD CONSTRAINT FK_EMPLEADOS FOREIGN KEY (JefeID) REFERENCES EMPLEADOS (JefeID)
GO
--LLAVES UNICAS
ALTER TABLE CLIENTES ADD CONSTRAINT UN_RFC_CTE UNIQUE(CteRFC)
GO
ALTER TABLE CLIENTES ADD CONSTRAINT UN_RFC_CURP UNIQUE(CteCurp)
GO
ALTER TABLE EMPLEADOS ADD CONSTRAINT UN_RFC_EMP UNIQUE(EmpRFC)
GO
ALTER TABLE EMPLEADOS ADD CONSTRAINT UN_RFC_CURP UNIQUE(EmpCurp)
GO
--RESTRICCION DE COMPROBACIÓN
ALTER TABLE CLIENTES ADD
CONSTRAINT CC_CTE_SEXO CHECK(CTESEXO IN('H','M')),
CONSTRAINT CC_CTE_RFC_CURP CHECK(CTERFC<>CTECURP),
CONSTRAINT CC_CLIENTES_RFC_LEN CHECK(LEN(CTERFC)=13)
GO
ALTER TABLE EMPLEADOS ADD
CONSTRAINT CC_EMP_RFC_CURP CHECK(EMPRFC<>EMPCURP)
GO
ALTER TABLE DETALLES ADD
CONSTRAINT CC_DET_PRECIO CHECK(PRECIO>0),
CONSTRAINT CC_DET_CANTIDAD CHECK(CANTIDAD>0)
GO
ALTER TABLE ARTICULOS ADD
CONSTRAINT CC_ART_PRECIO CHECK(ARTPRECIO>0)
GO
ALTER TABLE VENTAS ADD
CONSTRAINT CC_VENTAS_FECHA CHECK(FECHA>'1-1-2018')
GO
--VALOR PREDEFINIDO
ALTER TABLE EMPLEADOS ADD
CONSTRAINT DC_EMP_DOM DEFAULT('Domicilio desconocido')FOR EMPDOMICILIO,
CONSTRAINT DC_EMP_TEL DEFAULT('SIN TELÉFONO')FOR EMPTELEFONO
GO
ALTER TABLE CLIENTES ADD
CONSTRAINT DC_CLIENTES_DOM DEFAULT('Domicilio desconocido')FOR CTEDOMICILIO,
CONSTRAINT DC_CLIENTES_TEL DEFAULT('SIN TELEFONO')FOR CTETELEFONO
GO
ALTER TABLE COLONIAS ADD
CONSTRAINT DC_COL_CP DEFAULT('00000')FOR COLCP
GO



