CREATE DATABASE PRESTAMOS
GO
USE PRESTAMOS
GO
CREATE TABLE ESTADOS(
EDOID INT NOT NULL,
EDONOMBRE NVARCHAR(20) NOT NULL
)
GO
CREATE TABLE MUNICIPIOS(
MUNID INT NOT NULL,
MUNNOMBRE NVARCHAR(20) NOT NULL,
EDOID INT NOT NULL
)
GO
CREATE TABLE COLONIAS(
COLID INT NOT NULL,
COLNOMBRE NVARCHAR(20) NOT NULL,
MUNID INT NOT NULL
)
GO
CREATE TABLE USUARIOS(
USUID INT NOT NULL,
USUNOMBRE NVARCHAR(20) NOT NULL,
USUAPELLIDOS NVARCHAR(50) NULL,
USUDOMICILIO NVARCHAR(50) NULL,
USUTELEFONO NVARCHAR(10) NULL,
USUCORREO NVARCHAR(50) NULL,
COLID INT NOT NULL
)
GO
CREATE TABLE SUCURSALES(
SUCID INT NOT NULL,
SUCNOMBRE NVARCHAR(20) NOT NULL,
SUCDOMICILIO NVARCHAR(50) NULL,
SUCTELEFONO NVARCHAR(10) NULL,
)
GO
CREATE TABLE EMPLEADOS(
EMPID INT NOT NULL,
EMPNOMBRE NVARCHAR(20) NOT NULL,
EMPAPELLIDOS NVARCHAR(50) NULL,
EMPTELEFONO NVARCHAR(10) NULL,
EMPCORREO NVARCHAR(50) NULL
)
CREATE TABLE TAMAÑOS(
TAMID INT NOT NULL,
TAMNOMBRE NVARCHAR(20) NOT NULL
)
GO
CREATE TABLE TIPOS(
TIPID INT NOT NULL,
TIPNOMBRE NVARCHAR(20) NOT NULL
)
GO
CREATE TABLE PIEZAS(
PIEID INT NOT NULL,
PIENOMBRE NVARCHAR(20) NOT NULL,
PIEDESCRIPCION NVARCHAR(200) NULL,
PIEVALOR NUMERIC(10,2) NOT NULL,
TAMID INT NOT NULL,
TIPID INT NOT NULL
)
GO
CREATE TABLE PRESTAMOS(
FOLIO INT NOT NULL,
FECHACAPTURA DATETIME NOT NULL,
MONTO NUMERIC(10,2) NOT NULL,
MENSUALIDADES INT NOT NULL,
SUCID INT NOT NULL,
USUID INT NOT NULL,
EMPREALIZO INT NOT NULL,
EMPEVALUO INT NOT NULL,
PIEID INT NOT NULL
)
GO
--LLAVES PRIMARIAS
ALTER TABLE ESTADOS ADD CONSTRAINT PK_ESTADOS PRIMARY KEY(EDOID)
GO
ALTER TABLE MUNICIPIOS ADD CONSTRAINT PK_MUNICIPIOS PRIMARY KEY(MUNID)
GO
ALTER TABLE COLONIAS ADD CONSTRAINT PK_COLONIAS PRIMARY KEY(COLID)
GO
ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY(USUID)
GO
ALTER TABLE SUCURSALES ADD CONSTRAINT PK_SUCURSALES PRIMARY KEY(SUCID)
GO
ALTER TABLE EMPLEADOS ADD CONSTRAINT PK_EMPLEADO PRIMARY KEY(EMPID)
GO
ALTER TABLE TAMAÑOS ADD CONSTRAINT PK_TAMAÑOS PRIMARY KEY(TAMID)
GO
ALTER TABLE TIPOS ADD CONSTRAINT PK_TIPOS PRIMARY KEY (TIPID)
GO
ALTER TABLE PIEZAS ADD CONSTRAINT PK_PIEZAS PRIMARY KEY(PIEID)
GO
ALTER TABLE PRESTAMOS ADD CONSTRAINT PK_PRESTAMOS PRIMARY KEY(FOLIO)
GO
--LLAVES EXTERNAS
ALTER TABLE MUNICIPIOS ADD CONSTRAINT FK_MUNICIPIOS_ESTADOS FOREIGN KEY (EDOID) REFERENCES ESTADOS(EDOID)
GO
ALTER TABLE COLONIAS ADD CONSTRAINT FK_COLONIAS_MUNICIPIOS FOREIGN KEY(MUNID) REFERENCES MUNICIPIOS(MUNID)
GO
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_COLONIAS FOREIGN KEY (COLID) REFERENCES COLONIAS(COLID)
GO
ALTER TABLE PIEZAS ADD CONSTRAINT FK_PIEZAS_TAMAÑOS FOREIGN KEY (TAMID) REFERENCES TAMAÑOS(TAMID),
CONSTRAINT FK_PIEZAS_TIPOS FOREIGN KEY(TIPID) REFERENCES TIPOS(TIPID)
GO
ALTER TABLE PRESTAMOS ADD CONSTRAINT FK_PRESTAMOS_SUCURSALES FOREIGN KEY (SUCID) REFERENCES SUCURSALES(SUCID),
CONSTRAINT FK_PRESTAMOS_EMPLEADOREALIZO FOREIGN KEY (EMPREALIZO) REFERENCES EMPLEADOS(EMPID),
CONSTRAINT FK_PRESTAMOS_EMPLEADOEVALUO FOREIGN KEY (EMPEVALUO) REFERENCES EMPLEADOS(EMPID),
CONSTRAINT FK_PRESTAMOS_PIEZAS FOREIGN KEY (PIEID) REFERENCES PIEZAS(PIEID),
CONSTRAINT FK_PRESTAMOS_USUARIOS FOREIGN KEY (USUID) REFERENCES USUARIOS(USUID)
GO
--LLAVES UNICAS
ALTER TABLE PRESTAMOS ADD CONSTRAINT UQ_PRESTAMOS_PIEID UNIQUE (PIEID)
GO
--VISTAS
CREATE VIEW VW_PIEZAS AS
SELECT 
P.PIEID, P.PIENOMBRE,P.PIEDESCRIPCION,P.PIEVALOR,
T.TAMID,T.TAMNOMBRE,
TI.TIPID, TI.TIPNOMBRE
FROM PIEZAS P
INNER JOIN TAMAÑOS T ON T.TAMID = P.TAMID
INNER JOIN TIPOS TI ON TI.TIPID = P.TIPID
GO
CREATE VIEW VW_MUNICIPIOS AS
SELECT 
M.MUNID, M.MUNNOMBRE,
E.EDOID, E.EDONOMBRE
FROM MUNICIPIOS M
INNER JOIN ESTADOS E ON E.EDOID = M.EDOID 
GO
CREATE VIEW VW_COLONIAS AS
SELECT
C.COLID,C.COLNOMBRE,
VWM.MUNID, VWM.MUNNOMBRE, VWM.EDOID,VWM.EDONOMBRE
FROM COLONIAS C
INNER JOIN VW_MUNICIPIOS VWM ON VWM.MUNID = C.MUNID
GO
CREATE VIEW VW_USUARIOS AS
SELECT
U.USUID, U.USUNOMBRE, U.USUAPELLIDOS, U.USUDOMICILIO,U.USUTELEFONO, U.USUCORREO,
VWC.COLID, VWC.COLNOMBRE, VWC.MUNID, VWC.MUNNOMBRE, VWC.EDOID, VWC.EDONOMBRE
FROM USUARIOS U
INNER JOIN VW_COLONIAS VWC ON VWC.COLID=U.COLID 
GO
CREATE VIEW VW_PRESTAMOS AS
SELECT
P.FOLIO, P.FECHACAPTURA,P.MONTO,P.MENSUALIDADES,
ValuadorID = EV.EMPID, ValuadorNombre = EV.EMPNOMBRE, ValuadorApellidos = EV.EMPAPELLIDOS, ValuadorTelefono = EV.EMPTELEFONO, ValuadorCorreo = EV.EMPCORREO,
RealizadorID = RE.EMPID, RealizadorNombre = RE.EMPNOMBRE, RealizadorApellidos = RE.EMPAPELLIDOS, RealizadorTelefono = RE.EMPTELEFONO,RealizadorCorreo = RE.EMPCORREO,
S.SUCID,S.SUCNOMBRE, S.SUCDOMICILIO, S.SUCTELEFONO,
VWP.PIEID, VWP.PIENOMBRE, VWP.PIEDESCRIPCION,VWP.PIEVALOR,VWP.TAMID, VWP.TAMNOMBRE, VWP.TIPID, VWP.TIPNOMBRE,
VWU.USUID, VWU.USUNOMBRE, VWU.USUAPELLIDOS, VWU.USUDOMICILIO, VWU.USUTELEFONO, VWU.USUCORREO, VWU.COLID, VWU.COLNOMBRE, VWU.MUNID, VWU.MUNNOMBRE,VWU.EDOID, VWU.EDONOMBRE
FROM PRESTAMOS P
INNER JOIN EMPLEADOS EV ON EV.EMPID = P.EMPEVALUO
INNER JOIN EMPLEADOS RE ON RE.EMPID = P.EMPREALIZO
INNER JOIN SUCURSALES S ON S.SUCID = P.SUCID 
INNER JOIN VW_PIEZAS VWP ON VWP.PIEID = P.PIEID
INNER JOIN VW_USUARIOS VWU ON VWU.USUID = P.USUID 








