/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.CallableStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Consultar extends javax.swing.JFrame {

    public Consultar() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupGeneros = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jlNombre = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jlDescripcion = new javax.swing.JLabel();
        jlTamaño = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        rbChico = new javax.swing.JRadioButton();
        rbMediano = new javax.swing.JRadioButton();
        jlPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jlFamilia = new javax.swing.JLabel();
        cbFamilia = new javax.swing.JComboBox<>();
        txtID = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        rbGrande = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArticulos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clientes");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jlNombre.setText("Nombre");

        jlDescripcion.setText("Descripcion");

        jlTamaño.setText("Tamaño");

        groupGeneros.add(rbChico);
        rbChico.setText("Chico");

        groupGeneros.add(rbMediano);
        rbMediano.setText("Mediano");

        jlPrecio.setText("Precio");

        jlFamilia.setText("Familia");

        cbFamilia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Abarrotes", "Verduras", "Lacteos", "Limpieza" }));
        cbFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFamiliaActionPerformed(evt);
            }
        });

        lblID.setText("ID");

        groupGeneros.add(rbGrande);
        rbGrande.setText("Grande");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlTamaño)
                        .addGap(95, 95, 95)
                        .addComponent(rbChico)
                        .addGap(18, 18, 18)
                        .addComponent(rbMediano)
                        .addGap(18, 18, 18)
                        .addComponent(rbGrande))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlDescripcion)
                            .addComponent(jlPrecio)
                            .addComponent(jlFamilia)
                            .addComponent(jlNombre))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDescripcion)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                                    .addComponent(txtPrecio)
                                    .addComponent(cbFamilia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addComponent(lblID)
                                .addGap(18, 18, 18)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnConsultar))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTamaño)
                    .addComponent(rbChico)
                    .addComponent(rbMediano)
                    .addComponent(rbGrande))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPrecio)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFamilia)
                    .addComponent(cbFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Precio", "Tamaño", "Familia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblArticulosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblArticulos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(350, 350, 350))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
     DefaultTableModel modeloTabla = (DefaultTableModel) tblArticulos.getModel();
    modeloTabla.setRowCount(0);
    
    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsmd;
    int columnas;
    
    String sql =  "SELECT artid, artnombre, artdescripcion, artprecio, arttamaño, f.famnombre " +
                 "FROM ARTICULOS a " +
                 "INNER JOIN FAMILIAS f ON a.famid = f.famid " +
                 "WHERE 1=1"; 
    if (!txtID.getText().trim().isEmpty()) {
        sql += " AND artid LIKE ?";
    }
    if (!txtNombre.getText().trim().isEmpty()) {
        sql += " AND artnombre LIKE ?";
    }
    if (!txtDescripcion.getText().trim().isEmpty()) {
        sql += " AND artdescripcion LIKE ?";
    }
    if (rbChico.isSelected()) {
        sql += " AND artTamaño = 'C'";
    } else if (rbMediano.isSelected()) {
        sql += " AND artTamaño = 'M'";
    } else if (rbGrande.isSelected()) {
        sql += " AND artTamaño = 'G'";
    }
    if (!txtPrecio.getText().trim().isEmpty()) {
        sql += " AND artprecio = ?";
    }
    if (cbFamilia.getSelectedIndex() > 0) { // Si no es "Seleccione"
        sql += " AND f.famnombre = ?";
    }
    
    try {
        Connection con = Conexion.getConexion();
        ps = con.prepareStatement(sql);
        
        int paramIndex = 1;
        if (!txtID.getText().trim().isEmpty()) {
            ps.setDouble(paramIndex++, Integer.parseInt(txtID.getText().trim()));
        }
        if (!txtNombre.getText().trim().isEmpty()) {
            ps.setString(paramIndex++, "%" + txtNombre.getText().trim() + "%");
        }
        if (!txtDescripcion.getText().trim().isEmpty()) {
            ps.setString(paramIndex++, "%" + txtDescripcion.getText().trim() + "%");
        }
        if (!txtPrecio.getText().trim().isEmpty()) {
            ps.setDouble(paramIndex++, Double.parseDouble(txtPrecio.getText().trim()));
        }
        if (cbFamilia.getSelectedIndex() > 0) {
            ps.setString(paramIndex++, cbFamilia.getSelectedItem().toString()); // Se compara con el nombre del tipo
        }
        
        rs = ps.executeQuery();
        rsmd = rs.getMetaData();
        columnas = rsmd.getColumnCount();
        
        while (rs.next()) {
            Object[] fila = new Object[columnas];
            for (int i = 0; i < columnas; i++) {
                fila[i] = rs.getObject(i + 1);
            }
            // Convertir código de tamaño a nombre legible
        String codTamaño = (String) fila[4];
        switch (codTamaño) {
        case "C":
            fila[4] = "Chico";
            break;
        case "M":
            fila[4] = "Mediano";
            break;
        case "G":
            fila[4] = "Grande";
            break;
    }
            
            modeloTabla.addRow(fila);
        }
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al consultar la tabla: " + e.getMessage());
    }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void cbFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFamiliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFamiliaActionPerformed

    private void tblArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblArticulosMouseClicked
        /*try{
            int fila = tblClientes.getSelectedRow();
            int id = Integer.parseInt(tblClientes.getValueAt(fila, 0).toString());
            
            PreparedStatement ps;
            ResultSet rs;
            
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT cliid,cliNombre, cliApellidos, cliSexo, CliLimiteCredito, tipid FROM CLIENTES WHERE cliid=?");
            ps.setInt(1, id);
            rs=ps.executeQuery();
            
            while(rs.next()){
                txtID.setText(String.valueOf(id));
                txtNombre.setText(rs.getString("cliNombre"));
                txtApellidos.setText(rs.getString("cliApellidos"));
                if(rs.getString("cliSexo").equals("M")){
                    rbMasculino.setSelected(true);
                }else if(rs.getString("cliSexo").equals("F")){
                    rbFemenino.setSelected(true);
                }       
                txtLimiteCredito.setText(rs.getString("cliLimiteCredito")); 
                int tipoId = rs.getInt("tipid"); // Obtener el número de la base de datos

                // Asegurar que el valor esté en el rango correcto
                if (tipoId >= 1 && tipoId <= 4) {
                 cbTipo.setSelectedIndex(tipoId); // Asignar el índice correspondiente
                } else {
                    cbTipo.setSelectedIndex(0); // Si el valor es inválido, seleccionar "Seleccione"
                }

            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error al asignar los valores "+e.getMessage());

        }*/
    }//GEN-LAST:event_tblArticulosMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbFamilia;
    private javax.swing.ButtonGroup groupGeneros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlDescripcion;
    private javax.swing.JLabel jlFamilia;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlPrecio;
    private javax.swing.JLabel jlTamaño;
    private javax.swing.JLabel lblID;
    private javax.swing.JRadioButton rbChico;
    private javax.swing.JRadioButton rbGrande;
    private javax.swing.JRadioButton rbMediano;
    private javax.swing.JTable tblArticulos;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    private void limpiar(){
        txtID.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");
        groupGeneros.clearSelection();
        txtPrecio.setText("");
        cbFamilia.setSelectedIndex(0);
       
    }
    
    

    
    
}
